#!/bin/bash

command="$1"
prompt="$2"

if [[ -z $command ]]; then
	echo "Usage: $0 command [prompt]"
	exit
fi

# store command history here
HISTFILE=~/.shellify_history

# trap keyboard interrupt (control-c)
trap '' SIGINT

# read command history from file
history -r

# run loop with prompt
while read -rep "$prompt" 2>&1 line
do
	[[ -z $line ]] && continue
	[[ $line == "clear" ]] && clear && break
	[[ $line == "exit" ]] && break

	# save line to history
	history -s "$line"

	# git'r done
	$command $line
done

# save history to file
history -a

exit
# Documentation
=pod

=head1 shellify(1)

Make any program into an interactive shell.

=head2 Usage

C<shellify <commandE<gt> [prompt]>

=head3 Example

Simple L<git-sh|https://github.com/rtomayko/git-sh>:

=begin html

<pre>
$ shellify git 'git> '
git> status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit (use -u to show untracked files)
git>
</pre>

=end html

